# Generated by Django 3.2.9 on 2021-11-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
